server:
  port: 8081

spring:
  datasource:
    username: root
    password: "@Ly135790"
    url: jdbc:mysql://localhost:3306/order_please?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.com:
      mapper: debug
      service: info
      controller: info

order-please:
  jwt:
    admin-secret-key: rHQgVzX6w+EZnCx7c8a2jP9GqM1S5d3yV0bW4fRwUk/e7p0tAoLXiNlKvBh=
    admin-ttl: 7200000
    admin-token-name: token
