server:
  port: 8081

spring:
  profiles:
    active: dev

  datasource:
    username: ${value.datasource.username}
    password: ${value.datasource.password}
    url: jdbc:mysql://${value.datasource.host}:${value.datasource.port}/${value.datasource.database}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    driver-class-name: ${value.datasource.driver-class-name}
  data:
    redis:
      host: ${value.redis.host}
      database: ${value.redis.database}
      port: ${value.redis.port}
      password: ${value.redis.password}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath: classpath:mapper/*.xml

logging:
  file:
    name: ./back_end/server/logs/record.log
  level:
    org.com:
      mapper: debug
      service: info
      controller: info

order-please:
  jwt:
    admin-secret-key: ${value.jwt.admin-secret-key}
    admin-ttl: ${value.jwt.admin-ttl}
    admin-token-name: ${value.jwt.admin-token-name}
    user-secret-key: ${value.jwt.user-secret-key}
    user-ttl: ${value.jwt.user-ttl}
    user-token-name: ${value.jwt.user-token-name}

  aliyun-oss:
    endpoint: ${value.aliyun-oss.endpoint}
    access-key-id: ${value.aliyun-oss.access-key-id}
    access-key-secret: ${value.aliyun-oss.access-key-secret}
    bucket-name: ${value.aliyun-oss.bucket-name}

  wechat:
    appid: ${value.wechat.appid}
    app-secret: ${value.wechat.app-secret}

